### PR TITLE
[WIP] Admin api sdk

### PR DESCRIPTION
**Pull request by allouis**
This an initial version of sdk for talking w/ the admin api.

This extends the got library with some custom code for authenticating against the admin api - this should give us lots of flexibility with the sdk and didn't require too much work. future iterations could definitely include extra methods for particular resources, or mapping from `got('resource')` to the correct url.

### CODE REVIEW

**Comment by kevinansfield** [comment]
@allouis I guess the use of `jsonwebtoken` already precludes client-side use so it's not such a big deal but I still wonder if we should use `fetch` directly rather than `got`. Using `fetch` would let us keep the networking side of things the same between this and the Content API SDK which will definitely need a client-side build where fetch can be easily polyfilled.

**Comment by kevinansfield** [comment]
D'oh 🙈 didn't realise Node.js doesn't have native fetch. This looks like a good substitute for got where we need multiple build targets though https://github.com/lquixada/cross-fetch

**Comment by allouis** [comment]
I was thinking to use fetch initially when I thought we'd roll both SDK's into one. but yeah like you say node doesn't have fetch and admin sdk should _never_ be used in a browser.

> keep the networking side of things the same between this and the Content API SDK

I'm not sure how much of a bonus this is for us - but happy to do it if you want.

I think it's okay to have slightly different stacks between node/browser content/admin

**Comment by kevinansfield** [comment]
> I'm not sure how much of a bonus this is for us

The main thing would be internal API consistency across the two SDKs. Say the API changes in the future and both the Content and Admin SDKs need updating - it would be nice not to have to work out the intricacies of two different networking libraries to make the same change.

**Comment by ErisDS** [comment]
Another option is https://github.com/visionmedia/superagent

It works in node and browser,  is super lightweight and very well maintained.

I'd advocate strongly for consistently using the same tool in all SDKs, even if that breaks consistency with our other tools (where we do consistently try to use got, heh)

**Pull request closed without merging**
